%MACRO myreport(lib,dsn,statvar);
PROC MEANS DATA=&lib..&dsn;
VAR &statvar;
RUN;
PROC PRINT DATA=&lib..&dsn;
RUN;
%MEND;

%MYREPORT(SASHELP,CLASS,AGE);
%MYREPORT(SASHELP,CLASS,HEIGHT);
%MYREPORT(SASHELP,CLASS,WEIGHT);
%MYREPORT(SASHELP,CARS,MSRP);