/* This SAS snippet creates a dataset named COURSE_INFO using the DATA statement.
It defines variables: STUDENT_NAME, STUDENT_GENDER, STUDENT_AGE, COURSE_CODE, and MAJOR.
The INPUT statement specifies the format of the data to be read. */
DATA COURSE_INFO;
	INPUT STUDENT_NAME $ STUDENT_GENDER $ STUDENT_AGE COURSE_CODE MAJOR $;
	CARDS;
John M 48 101 STAT
Peter M 58 101 HIST
Liz F 25 201 STAT
Joe M 28 301 ENGG
Mike M 34 202 HIST
Pat F 34 201 STAT
Jil F 45 101 HIST
Tom M 56 301 ENGG
;
RUN;

/* This SAS snippet uses PROC REPORT to generate a tabular report of the COURSE_INFO dataset. */
PROC REPORT DATA=COURSE_INFO;
	COLUMNS STUDENT_NAME STUDENT_GENDER STUDENT_AGE COURSE_CODE MAJOR;
	DEFINE STUDENT_NAME / DISPLAY;
	DEFINE STUDENT_GENDER / ORDER;
	DEFINE STUDENT_AGE / DISPLAY;
	DEFINE COURSE_CODE / DISPLAY;
	DEFINE MAJOR / DISPLAY;
RUN;

/* This SAS snippet uses PROC REPORT to generate a tabular report showing the mean age by gender from the COURSE_INFO dataset. */
PROC REPORT DATA=COURSE_INFO;
	COLUMNS STUDENT_GENDER STUDENT_AGE;
	DEFINE STUDENT_GENDER / GROUP;
	DEFINE STUDENT_AGE / ANALYSIS MEAN;
RUN;

/* This SAS snippet uses PROC REPORT to generate a tabular report of selected variables from the SASHELP.CARS dataset. */
PROC REPORT DATA=sashelp.cars;
	COLUMNS MAKE MODEL TYPE ORIGIN MSRP;
	DEFINE MAKE / DISPLAY;
	DEFINE MODEL / DISPLAY WIDTH=20 FLOW;
	DEFINE TYPE / DISPLAY;
	DEFINE ORIGIN / DISPLAY;
	DEFINE MSRP / DISPLAY;
RUN;